---
- name: Install packages for a basic machine with X
  package:
    name:
      - dmenu
      - chromium
      - firefox
      - cups
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
      - rxvt-unicode
      - rxvt-unicode-terminfo
      - xorg
      - xorg-xinit
  tags:
    - x-basic
    - update

- name: Enable the cups-browsed service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: cups-browsed
    state: started
  tags:
    - x-basic
