---
- name: Install packages for a basic machine with X
  package:
    name:
      - firefox
      - cups
      - libu2f-host
      - i3
      - rxvt-unicode
      - rxvt-unicode-terminfo
      - xorg
- name: Enable the cups-browsed service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: cups-browsed
    state: started
  tags:
    - x-basic
