---
- name: Setup feh background
  block:
    - name: Install feh
      package:
        name:
          - feh
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/penguin_emperor.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
  tags:
    - feh
    - feh-cisa
