* ansible-home

Forked from [jsf9k/ansible-arch-install][https://github.com/jsf9k/ansible-arch-install]

Ansible code to configure and maintain my home network.  The code here
assumes that all devices have been installed via
[sesamemucho/ansible-arch-install](https://github.com/sesamemucho/ansible-arch-install)
or
[jsf9k/ansible-raspi-install](https://github.com/jsf9k/ansible-raspi-install).

** Usage

Put the appropriate passphrase into the ansible vault password file:
~/.vault_pass.txt

Make sure group_vars/all.txt has entries for the following variables:

user_name: your user name
user_group: your user group
user_home: Home directory (probably /home/user_name)
git_user_fullname: 'Full name for git'
git_user_email: 'email for git'

Put any github repos you want to check out here.
the 'dest' key indicates the destination directory, starting under
user_home.

If you don't have any github repos to check out, comment out
'my_github:' and any following repositories.

my_github:
  - repo: 'git@github.com:sesamemucho/emacs-init.git'
    dest: '.emacs.d'
  - repo: 'git@github.com:sesamemucho/emacs-packages'
    dest: 'myemacs'


Populate `inventory.yml` and run `site.yml`:

```console
ansible-playbook -i inventory.yml site.yml
```

To update all packages, run `update.yml`:
```console
ansible-playbook -i inventory.yml update.yml
```

If you aren't in the United States, you may want to update the
--country setting in roles/init/tasks/main.yml

** After first install

- Go through and update/add yadm ## tags.
