---
- name: Install yadm dotfile manager

  block:
    - name: Check out from git
      ansible.builtin.git:
        repo: https://github.com/TheLocehiliosan/yadm.git
        dest: '{{ lookup("env", "HOME") }}/Projects/readonly-repos/yadm'
        force: yes

    - name: Set repo owner
      ansible.builtin.file:
        path: '{{ lookup("env", "HOME") }}/Projects/readonly-repos/yadm'

    - name: Make symlink to yadm executable
      ansible.builtin.file:
        src: '{{ lookup("env", "HOME") }}/Projects/readonly-repos/yadm/yadm'
        dest: /usr/local/bin/yadm
        state: link
      become_user: root

    - name: Clone dofiles repo
      ansible.builtin.command:
        cmd: yadm clone https://github.com/sesamemucho/yadm-configs
        creates: '{{ lookup("env", "HOME") }}/.local/share/yadm/repo.git'

    - name: Activate yadm 1
      ansible.builtin.command:
        cmd: yadm restore --staged '{{ lookup("env", "HOME") }}'
        creates: '{{ lookup("env", "HOME") }}/.bash.d'

    - name: Activate yadm 2
      ansible.builtin.command:
        cmd: yadm restore '{{ lookup("env", "HOME") }}'
        creates: '{{ lookup("env", "HOME") }}/.bash.d'

  become: true
  become_user: '{{ lookup("env", "HOME") }}'

  tags:
    dotfiles

- name: Install emacs dotfiles
  ansible.builtin.git:
    repo: https://github.com/sesamemucho/emacs-init
    dest: '{{ lookup("env", "HOME") }}/.emacs.d'

  become: true
  become_user: bob

  tags:
    dotfiles

