---
- name: Setup xdm
  block:
    - name: Install packages for a basic machine with X
      package:
        name:
          - xdm-archlinux
    - name: Replace dummy text with machine name
      replace:
        path: /etc/X11/xdm/archlinux/Xresources
        regexp: CLIENTHOST
        replace: '{{ ansible_hostname }}'
    - name: Enable and start the xdm service
      systemd:
        name: xdm-archlinux
        enabled: yes
        state: started
  tags:
    - xdm
