
---
- name: Customizable setup
  block:
    - name: Install things that may have customized dotfiles
      community.general.pacman:
        name:
          - emacs
          - tmux
          - syncthing
          - unison
        extra_args: --noconfirm
        update_cache: yes

      become: true
  tags:
    - customizable
    - update
 
