
---
- name: Customizable setup
  block:
    - name: Install things that may have customized dotfiles
      community.general.pacman:
        name:
          - emacs
          - tmux
          - syncthing
          - unison
        extra_args: --noconfirm
        update_cache: yes

      become: true
  tags:
    - customizable
    - update
 
- name: Clone repos from github
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: '{{ user_home }}/{{ item.dest }}'
  loop:
    "{{ my_github }}"

  when: my_github is defined
  become: true
  become_user: "{{ user_name }}"

  tags:
    - git
