---
- name: Rank Arch mirrors
  block:
    - name: Install the reflector package (for rankmirrors)
      community.general.pacman:
        name:
          - reflector
        extra_args: --noconfirm
        update_cache: yes

    - name: filter the fastest mirrors that support HTTPS
      shell: reflector --country "United States" --verbose --latest 10 --sort rate | awk -e '! /rsync/ {print}' > /etc/pacman.d/mirrorlist
  become: true
  tags:
    - mirrors

- name: Start with updated system
  community.general.pacman:
    upgrade: yes
    extra_args: --noconfirm
  become: true
  tags:
    - init

# Currently, the pacman module doesn't have the ability to deal with
# package conflicts
- name: Remove iptables for iptables-nft
  shell: yes | pacman -S iptables-nft
  become: true
  tags:
    - init

