---
- name: Rank Arch mirrors
  block:
    - name: Install the reflector package (for rankmirrors)
      community.general.pacman:
        name:
          - reflector
        update_cache: yes
    - name: filter the fastest mirrors that support HTTPS
      shell: reflector --verbose --latest 10 --sort rate | awk -e '! /rsync/ {print}' > /etc/pacman.d/mirrorlist
  tags:
    - mirrors
