---
- name: Install git and stow
  package:
    name:
      - git
      - stow
- name: Checkout .dotfiles repository
  git:
    repo: git@github.com:jsf9k/.dotfiles.git
    dest: /home/{{ ansible_user }}/.dotfiles
    accept_hostkey: yes
  become_user: "{{ ansible_user }}"
  notify:
    - Delete existing config files
    - Install dotfiles
  tags:
    - dotfiles
